### PR TITLE
improve performance

### PR DESCRIPTION
**Pull request by Uzlopak**
Hi @lukeed ,

with this PR we generate a id-function on the fly.  There are also various changes like avoiding substring calls and initializing the HEX-Lookup-Table with index 0.

before:
```
Benchmark (length = 16):
  hexoid               x 189,320,225 ops/sec ±0.34% (95 runs sampled)

Benchmark (length = 25):
  hexoid               x 175,288,431 ops/sec ±0.58% (96 runs sampled)

Benchmark (length = 36):
  hexoid               x 163,136,858 ops/sec ±0.54% (97 runs sampled)
```

after:
```
Benchmark (length = 16):
  hexoid               x 382,579,366 ops/sec ±0.64% (97 runs sampled)

Benchmark (length = 25):
  hexoid               x 342,972,348 ops/sec ±0.81% (97 runs sampled)

Benchmark (length = 36):
  hexoid               x 310,474,341 ops/sec ±0.77% (90 runs sampled)
```

Benchmarks made on node v14.19.1

@mcollina
@kibertoad

### CODE REVIEW

**Comment by lukeed** [comment]
Hi there, thanks for the PR. Can you add all this to a new “src/unsafe.js” file? Because this uses `new Function` this isn’t usable in runtimes like Cloudflare Workers

**Comment by Uzlopak** [comment]
@lukeed 
I am kind of unfamiliar with modul-javascript or what this is, and also your toolchain. :)
Can you please take it over?

Some performance gain could be also achieved for the "safe"-version like this:

```javascript
var i=0,HEX=[],r=Math.random;
while (i<256) HEX[i]=(256+i++).toString(16).substring(1);

export default function (len) {
	len||(len=16);
	var str='',lh =((1+len)>>1)-1,num=lh;
	while (num--) str += HEX[255*Math.random()|0];
	return function () {
		if (num === 255) {
			str=''; num=lh;
			while (num--) str += HEX[255*Math.random()|0];
		}
		return str + HEX[++num];
	};
}
```

**Comment by lukeed** [comment]
If you just add a new file I’ll take care of the rest :)

**Comment by Uzlopak** [comment]
done

**Comment by lukeed** [comment]
I think something is off with the index tracking? I'm running the collisions script (`node test/collisions.js 8 10000000`) and I'm getting 11k to 15k collisions per 10M items. When I run it on the base branch, I get 9.2k to 10.3k collisions per 10M items.

**Comment by Uzlopak** [comment]
Ok.. odd length fails now. Any wish how to solve it? I assume, that was the original reason for doing the substring?

**Comment by Uzlopak** [comment]
Or was it already broken before?

**Comment by lukeed** [comment]
Right, that looks more correct, but I also realized that odd-numbered lengths are not respected. That's part of what the substring was for previously.

Updated the benchmark usage too, btw.

**Comment by lukeed** [comment]
Odd lengths worked previously. Updating the base branch w/ cherry picked commits

**Comment by Uzlopak** [comment]
I think i could unify both, normal and unsafe, and enable unsafe by setting a second parameter to true. Should increase the maintanability of the code...

**Comment by lukeed** [comment]
I prefer the multiple files – doesn't affect maintainability at all. Plus _any_ presence of `new Function` is a violation in Workers, regardless of its code path execution

**Comment by Uzlopak** [comment]
An ok. Didnt know that.

**Comment by Uzlopak** [comment]
@lukeed can you have look at it,plz?

**Comment by Uzlopak** [comment]
Can we call it something different than unsafe? It does not really sound appealing to use "unsafe". I am currently thinking how we could name it.

**Comment by Uzlopak** [comment]
Can we call it `jit`?

**Comment by Uzlopak** [comment]
@lukeed 
Whats up?

**Comment by lukeed** [comment]
Sorry traveling

**Comment by Uzlopak** [comment]
Yeah enjoy your travelling ;). I am currently in Paris travelling. I was just wondering if there is a technical reason for stalling this PR ;).

So again: Enjoy your travelling. :)

**Comment by Uzlopak** [comment]
I renamed unsafe to jit

**Comment by Uzlopak** [comment]
@lukeed 

Are you taking a sabbatical :)?

**Comment by Uzlopak** [comment]
Closing due to inactivity. I also adapted my changes directly into fastify-multipart.

**Pull request closed without merging**
